server:
  port: 8090
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.82.100
  rabbitmq:
    virtual-host: /test
    username: root
    password: root
    host: 192.168.82.100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
sat:
  jwt:
    pubKeyPath: /Users/bystander/id_rsa.pub # 公钥地址
    cookieName: SAT_TOKEN # cookie的名称